/*
 * @describe: 中文包
 * @Author: superDragon
 * @Date: 2019-08-29 17:49:22
 * @LastEditors: xkloveme
 * @LastEditTime: 2023-02-10 16:24:02
 */

module.exports = {
  LANG: 'zh_CN',
  WELECOME: `欢迎使用WATONE CLI`,
  SHOW_VERSION: '版本信息',
  DOC_LINK: '文档链接',
  DOC: '文档',
  LINK: '链接',
  BUILD: '打包资源',
  CLONE: '克隆预制的模版',
  SERVER: '启动项目',
  SERACH: '关键字搜索',
  SERACH_DESC: '关键字搜索服务',
  BAIDU_DESC: '百度搜索',
  GOOGLE_DESC: '谷歌搜索',
  SOUGOU_DESC: '搜狗搜索',
  GITHUB_DESC: 'github搜索',
  IP: '获取本机ip',
  OPEN: '打开url',
  HTTP: '启动服务',
  HTTP_DESC: 'HTTP静态文件服务',
  HTTP_PORT: '启动服务端口',
  HTTP_OPEN: '是否打开浏览器',
  HTTP_URL: '启动目录',
  HELP: '帮助信息',
  HELP_DESC: '推荐使用node 16.16.0, pnpm >= 7.11.0',
  WEATHER: '天气服务',
  WEATHER_DESC: '默认获取当前地区的天气数据',
  DEV_DESC: '项目运行快捷命令',
  BUILD_DESC: '打包快捷命令',
  TIME: '时间转换',
  QRCODE_DESC: '内容生成二维码',
  TRANSLATION_DESC: '输入内容进行翻译',
  IP_DESC: '获取本机IP',
  OPEN_DESC: '浏览器打开URL链接',
  NO_COMMAND: '命令不存在',
  INIT_DESC: '初始化一个项目',
  SKIN_DESC: 'H5 APP 换皮',
  INIT_OPTION_FORCE: '初始化一个项目(强制覆盖)',
  GREETING_GUIDE: '开始新建一个模版项目,请选择对应模版',
  NPM_DESC:'NPM、YARN、PNPM换源',
  NPM_GUIDE:'上下按键切换源',
  NPM_MESSAGE:'请选择哪个命令要换源',
  NPM_SUCCESS:'您已成功使用 ',
  APP_DESC: '查看项目发布情况',
  AI_DESC:'人工智能Open AI',
  NETWORK_DISCONNECT: '您已断网！所需服务需要连接到互联网',
  NETWORK_DISCONNECT_SUG: '请确认您的设备处于网络可访问的环境中',
  NETWORK_DISCONNECTWATONE_SUG:'您处于非公司网络中,模版将会从互联网拉取',
  NETWORK_DISCONNECTWATONE_SUCCESS:'您处于公司网络中,模版将会从公司仓库拉取',
  LOADING_FROM_CLOUD: '正在拉取云端数据，请稍候',
  INPUT_INVALID: '输入不符合规范',
  PLEASE_INPUT: '请输入',
  PLEASE_INPUT_NUM_DESC: '请选择一个数字指定',
  PLEASE_INPUT_NUM: '请输入数字',
  PLEASE_INPUT_RIGHR_NUM: '请输入正确的数字',
  PLEASE_SELECT: '请选择一个',
  PLEASE_SELECT_DESC: '按上下键选择',
  FORCE_OPTION:'INIT 命令强制更新',
  LS_OPTION:'NPM 命令列出来已有源地址',
  PORT_OPTION:'HTTP 命令指定端口',
  HTTP_OPEN_OPTION:'HTTP 命令是否打开浏览器(默认打开)',
  HTTP_URL_OPTION:'HTTP 命令指定启动路径',
  GAME_DESC:'PLAY 命令',
  META_TEMPLATE_ERROR: '获取模版 Meta 信息出错',
  DOWNLOAD_TEMPLATE_ERROR: '下载模版出错，请检查当前网络',
  LOADING_EXPORT_PROJECT: '成功下载工程',
  RENDER_TEMPLATE_ERROR: '模板渲染出错',
  INIT_SUCCESS: '项目已创建成功',
  INIT_NEXT_GUIDE: '您可以操作如下命令快速开始开发工程',
  UPDATE_TIPS: 'WATONE CLI 有新的版本更新，您可以通过 `npm update -g @watone/wt-cli` 命令更新版本!',
};